version: "3.3"
services:  
  db:
    image: postgres:latest
    volumes:
     - ./backup_data/db:/var/lib/postgresql/data
    environment:
     - POSTGRES_DB=burrowwatch
     - POSTGRES_USER=burrowuser
     - POSTGRES_PASSWORD=Burr0wU$$3r
    networks:
     - db-network

  backend:
    build: ./server
    volumes:
     - ./server:/app
    depends_on:
     - db
    links:
     - db:db
    networks:
     - db-network
  
  frontend:
    build: ./client
    volumes:
      - ./client:/app
    ports:
      - 80:80
    depends_on:
      - backend
  
  nginx_backend_server:
    build: ./nginx-backend-server
    ports:
        - 8000:8000
    depends_on:
      - backend

networks:
  db-network:
    driver: bridge
