# Generated by Django 3.2.13 on 2022-06-15 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Burrow',
            fields=[
                ('uuid', models.BigAutoField(primary_key=True, serialize=False)),
                ('owl_count', models.IntegerField()),
                ('date_discovered', models.DateField()),
                ('last_checked', models.DateField()),
                ('last_checked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
